"""Small mesh kernel used as a no-dependency CAD fallback."""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from pathlib import Path

Vec3 = tuple[float, float, float]
Face = tuple[int, int, int]


@dataclass
class Mesh:
    vertices: list[Vec3] = field(default_factory=list)
    faces: list[Face] = field(default_factory=list)

    def add_vertex(self, point: Vec3) -> int:
        self.vertices.append(point)
        return len(self.vertices) - 1

    def add_face(self, a: int, b: int, c: int) -> None:
        self.faces.append((a, b, c))

    def merge(self, other: "Mesh") -> None:
        offset = len(self.vertices)
        self.vertices.extend(other.vertices)
        self.faces.extend((a + offset, b + offset, c + offset) for a, b, c in other.faces)

    def write_obj(self, path: Path) -> None:
        lines = ["# Generated by CAD_Agent mesh fallback"]
        lines.extend(f"v {x:.6f} {y:.6f} {z:.6f}" for x, y, z in self.vertices)
        lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in self.faces)
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    def write_stl(self, path: Path, name: str = "cad_agent_model") -> None:
        lines = [f"solid {name}"]
        for a, b, c in self.faces:
            p1, p2, p3 = self.vertices[a], self.vertices[b], self.vertices[c]
            normal = _normal(p1, p2, p3)
            lines.append(f"  facet normal {normal[0]:.6f} {normal[1]:.6f} {normal[2]:.6f}")
            lines.append("    outer loop")
            for point in (p1, p2, p3):
                lines.append(f"      vertex {point[0]:.6f} {point[1]:.6f} {point[2]:.6f}")
            lines.append("    endloop")
            lines.append("  endfacet")
        lines.append(f"endsolid {name}")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def box_mesh(width: float, depth: float, height: float, origin: Vec3 = (0, 0, 0)) -> Mesh:
    x0, y0, z0 = origin[0] - width / 2, origin[1] - depth / 2, origin[2]
    x1, y1, z1 = origin[0] + width / 2, origin[1] + depth / 2, origin[2] + height
    mesh = Mesh()
    ids = [
        mesh.add_vertex(point)
        for point in (
            (x0, y0, z0),
            (x1, y0, z0),
            (x1, y1, z0),
            (x0, y1, z0),
            (x0, y0, z1),
            (x1, y0, z1),
            (x1, y1, z1),
            (x0, y1, z1),
        )
    ]
    for face in (
        (0, 1, 2),
        (0, 2, 3),
        (4, 6, 5),
        (4, 7, 6),
        (0, 4, 5),
        (0, 5, 1),
        (1, 5, 6),
        (1, 6, 2),
        (2, 6, 7),
        (2, 7, 3),
        (3, 7, 4),
        (3, 4, 0),
    ):
        mesh.add_face(ids[face[0]], ids[face[1]], ids[face[2]])
    return mesh


def tapered_cylinder_mesh(
    radius_top: float,
    radius_bottom: float,
    height: float,
    origin: Vec3,
    axis: Vec3 | None = None,
    segments: int = 24,
) -> Mesh:
    mesh = Mesh()
    direction = _normalize(axis or (0, 0, height))
    if axis is None:
        axis = (0, 0, height)
    end = (origin[0] + axis[0], origin[1] + axis[1], origin[2] + axis[2])
    side_a = _cross(direction, (0, 1, 0))
    if sum(value * value for value in side_a) < 1e-9:
        side_a = _cross(direction, (1, 0, 0))
    side_a = _normalize(side_a)
    side_b = _normalize(_cross(direction, side_a))

    bottom_center = mesh.add_vertex(origin)
    top_center = mesh.add_vertex(end)
    bottom: list[int] = []
    top: list[int] = []
    for index in range(segments):
        angle = 2 * math.pi * index / segments
        cos_a, sin_a = math.cos(angle), math.sin(angle)
        bottom_offset = _add(_scale(side_a, radius_bottom * cos_a), _scale(side_b, radius_bottom * sin_a))
        top_offset = _add(_scale(side_a, radius_top * cos_a), _scale(side_b, radius_top * sin_a))
        bottom.append(mesh.add_vertex(_add(origin, bottom_offset)))
        top.append(mesh.add_vertex(_add(end, top_offset)))
    for index in range(segments):
        nxt = (index + 1) % segments
        mesh.add_face(bottom_center, bottom[nxt], bottom[index])
        mesh.add_face(top_center, top[index], top[nxt])
        mesh.add_face(bottom[index], bottom[nxt], top[nxt])
        mesh.add_face(bottom[index], top[nxt], top[index])
    return mesh


def sphere_mesh(radius: float, origin: Vec3, lat_segments: int = 24, lon_segments: int = 48) -> Mesh:
    mesh = Mesh()
    rings: list[list[int]] = []
    top = mesh.add_vertex((origin[0], origin[1], origin[2] + radius))
    bottom = mesh.add_vertex((origin[0], origin[1], origin[2] - radius))

    for lat_index in range(1, lat_segments):
        phi = math.pi * lat_index / lat_segments
        z = radius * math.cos(phi)
        ring_radius = radius * math.sin(phi)
        ring: list[int] = []
        for lon_index in range(lon_segments):
            theta = 2 * math.pi * lon_index / lon_segments
            ring.append(
                mesh.add_vertex(
                    (
                        origin[0] + ring_radius * math.cos(theta),
                        origin[1] + ring_radius * math.sin(theta),
                        origin[2] + z,
                    )
                )
            )
        rings.append(ring)

    first_ring = rings[0]
    last_ring = rings[-1]
    for lon_index in range(lon_segments):
        nxt = (lon_index + 1) % lon_segments
        mesh.add_face(top, first_ring[lon_index], first_ring[nxt])
        mesh.add_face(bottom, last_ring[nxt], last_ring[lon_index])

    for lat_index in range(len(rings) - 1):
        current = rings[lat_index]
        below = rings[lat_index + 1]
        for lon_index in range(lon_segments):
            nxt = (lon_index + 1) % lon_segments
            mesh.add_face(current[lon_index], below[lon_index], below[nxt])
            mesh.add_face(current[lon_index], below[nxt], current[nxt])
    return mesh


def bezier_sweep_mesh(control_points: list[Vec3], radius: float, segments: int = 56, ring_size: int = 18) -> Mesh:
    path = [_quadratic_bezier(control_points, index / (segments - 1)) for index in range(segments)]
    mesh = Mesh()
    rings: list[list[int]] = []
    for point in path:
        ring: list[int] = []
        for ring_index in range(ring_size):
            angle = 2 * math.pi * ring_index / ring_size
            ring.append(mesh.add_vertex((point[0], point[1] + radius * math.cos(angle), point[2] + radius * math.sin(angle))))
        rings.append(ring)
    for index in range(segments - 1):
        for ring_index in range(ring_size):
            nxt = (ring_index + 1) % ring_size
            mesh.add_face(rings[index][ring_index], rings[index + 1][ring_index], rings[index + 1][nxt])
            mesh.add_face(rings[index][ring_index], rings[index + 1][nxt], rings[index][nxt])
    return mesh


def curved_surface_mesh(control_grid: list[list[Vec3]], thickness: float, u_steps: int = 36, v_steps: int = 24) -> Mesh:
    mesh = Mesh()
    front: list[list[int]] = []
    back: list[list[int]] = []
    for ui in range(u_steps):
        u = ui / (u_steps - 1)
        front_row: list[int] = []
        back_row: list[int] = []
        for vi in range(v_steps):
            v = vi / (v_steps - 1)
            point = _bilinear_grid(control_grid, u, v)
            front_row.append(mesh.add_vertex(point))
            back_row.append(mesh.add_vertex((point[0], point[1] - thickness, point[2])))
        front.append(front_row)
        back.append(back_row)
    for ui in range(u_steps - 1):
        for vi in range(v_steps - 1):
            _quad(mesh, front[ui][vi], front[ui + 1][vi], front[ui + 1][vi + 1], front[ui][vi + 1])
            _quad(mesh, back[ui][vi + 1], back[ui + 1][vi + 1], back[ui + 1][vi], back[ui][vi])
    for ui in (0, u_steps - 1):
        for vi in range(v_steps - 1):
            _quad(mesh, front[ui][vi], front[ui][vi + 1], back[ui][vi + 1], back[ui][vi])
    for vi in (0, v_steps - 1):
        for ui in range(u_steps - 1):
            _quad(mesh, front[ui][vi], back[ui][vi], back[ui + 1][vi], front[ui + 1][vi])
    return mesh


def _quad(mesh: Mesh, a: int, b: int, c: int, d: int) -> None:
    mesh.add_face(a, b, c)
    mesh.add_face(a, c, d)


def _quadratic_bezier(points: list[Vec3], t: float) -> Vec3:
    if len(points) == 3:
        a, b, c = points
        return (
            (1 - t) ** 2 * a[0] + 2 * (1 - t) * t * b[0] + t**2 * c[0],
            (1 - t) ** 2 * a[1] + 2 * (1 - t) * t * b[1] + t**2 * c[1],
            (1 - t) ** 2 * a[2] + 2 * (1 - t) * t * b[2] + t**2 * c[2],
        )
    left = points[:]
    while len(left) > 1:
        left = [
            (
                left[i][0] * (1 - t) + left[i + 1][0] * t,
                left[i][1] * (1 - t) + left[i + 1][1] * t,
                left[i][2] * (1 - t) + left[i + 1][2] * t,
            )
            for i in range(len(left) - 1)
        ]
    return left[0]


def _bilinear_grid(grid: list[list[Vec3]], u: float, v: float) -> Vec3:
    rows = len(grid)
    cols = len(grid[0])
    ru = min(rows - 2, int(u * (rows - 1)))
    cv = min(cols - 2, int(v * (cols - 1)))
    local_u = u * (rows - 1) - ru
    local_v = v * (cols - 1) - cv
    p00, p10 = grid[ru][cv], grid[ru + 1][cv]
    p01, p11 = grid[ru][cv + 1], grid[ru + 1][cv + 1]
    return tuple(
        (1 - local_u) * (1 - local_v) * p00[i]
        + local_u * (1 - local_v) * p10[i]
        + (1 - local_u) * local_v * p01[i]
        + local_u * local_v * p11[i]
        for i in range(3)
    )  # type: ignore[return-value]


def _normal(a: Vec3, b: Vec3, c: Vec3) -> Vec3:
    ab = (b[0] - a[0], b[1] - a[1], b[2] - a[2])
    ac = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
    cross = (
        ab[1] * ac[2] - ab[2] * ac[1],
        ab[2] * ac[0] - ab[0] * ac[2],
        ab[0] * ac[1] - ab[1] * ac[0],
    )
    length = math.sqrt(sum(value * value for value in cross)) or 1.0
    return cross[0] / length, cross[1] / length, cross[2] / length


def _add(a: Vec3, b: Vec3) -> Vec3:
    return a[0] + b[0], a[1] + b[1], a[2] + b[2]


def _scale(a: Vec3, value: float) -> Vec3:
    return a[0] * value, a[1] * value, a[2] * value


def _cross(a: Vec3, b: Vec3) -> Vec3:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _normalize(a: Vec3) -> Vec3:
    length = math.sqrt(sum(value * value for value in a))
    if length < 1e-9:
        return (0, 0, 0)
    return a[0] / length, a[1] / length, a[2] / length
